RadeonOpenCompute/ROCm-OpenCL-Driver

- CMakeLists.txt
- src/driver/AmdCompiler.cpp
Change-Id: Ief7e0113297cf19b7567a86f17c14d57086ea839
> Add CMake option GENERIC_IS_ZERO to use the new address space mapping

- src/driver/AmdCompiler.cpp
- src/driver/AmdCompiler.h
- src/driver/CMakeLists.txt
To switch on in-process compilation Compiler::SetInProcess() should be called on the invoker's side.
> [in-process] 1st stage: compilation cl->bc

- src/driver/AmdCompiler.cpp
This patch fixes an internal OpenCL test.
> [in-process] Fix error handling.

- src/driver/AmdCompiler.cpp
[Issue] https://github.com/RadeonOpenCompute/ROCm-OpenCL-Driver/issues/13
[Solution]
Filter out cc1 option -disable-free, which is set by default and contradictory to in-process compilation.
[Description]
If -disable-free is set clang buries its pointers into its own arena and memory is not released till app's exit. That leads to memory leaks after every compilation.
Contrariwise after every compilation by means of Clang Driver API (when clang app is being forked) memory releases with finishing clang process. Hence there is no need in filtering out -disable-free option on this path.
> [in-process][fix] Memory leaks due to clang's CompilerInstance::ExecuteAction()

- src/driver/AmdCompiler.cpp
lld is forked due to segfault in-process.
Testing done: OCL conformance 1.2 buffers.
> [in-process] 3rd stage - clBuild / CompileAndLinkExecutable

- src/driver/AmdCompiler.cpp
Fix for [[#21](https://github.com/RadeonOpenCompute/ROCm-OpenCL-Driver/issues/21)]
> [in-process] [fix] [#21] -mllvm options are not being parsed

- src/driver/AmdCompiler.cpp
+ InitDriver
+ PrepareCompiler
testing: ocl conformance 1.2 with export AMD_OCL_IN_PROCESS=1
> [in-process] Code refactoring

- src/driver/AmdCompiler.cpp
- src/driver/AmdCompiler.h
+ Add Compiler* to class Data.
+ Refactor all Data's inheritors.
+ Add a few missing setters and getters to class Compiler.
+ Refactor functions, dealing with env. vars.
> Code refactoring

- src/driver/AmdCompiler.cpp
DiagnosticHandler couldn't be implemented as class member function, thus left as static global, but a bit changed.
Pointer to AMDGPUCompiler is passed to DiagnosticHandler in order to use its stream for output.
EmitLinkerError moved to class AMDGPUCompiler.
> Linker Diagnostic refactoring

- src/driver/AmdCompiler.cpp
https://github.com/RadeonOpenCompute/ROCm-OpenCL-Driver/issues/26
testing: OCL Conformance 1.2 basic, compiler in both modes (in-process and driver) with AMD_OCL_LOG_LEVEL=3 and AMD_OCL_PRINT_LOG=1
> [#26] Print clang Driver options, phases with mode used

- src/driver/AmdCompiler.cpp
https://github.com/RadeonOpenCompute/ROCm-OpenCL-Driver/issues/37
> [#37] Workaround for flawed Driver::BuildCompilation(...) implementation

- src/driver/AmdCompiler.cpp
Updated Redirects. See more here: https://reviews.llvm.org/rL313155
> Necessary updates to fix the build.

- src/driver/AmdCompiler.cpp
> Rename tool_output_file to ToolOutputFile, NFC

- src/driver/AmdCompiler.cpp
- src/driver/CMakeLists.txt
Reverts RadeonOpenCompute/ROCm-OpenCL-Driver#47
> Revert "Revert "[in-process] Enabling lld in-process""

- src/driver/AmdCompiler.cpp
- src/driver/AmdCompiler.h
- src/driver/CMakeLists.txt
> roc-1.6.4 updates

- src/driver/AmdCompiler.cpp
- src/driver/AmdCompiler.h
- src/driver/CMakeLists.txt
> roc-1.7.0 updates

- src/driver/AmdCompiler.cpp
1. clang's -D and -I options are transformed the following way:
-Dxyz=1 => -Wa,-defsym,xyz=1 => (by clang) -defsym xyz=1
-I/path => -Wa,-I,/path => (by clang) -I /path
2. [misc] Flushing log fix (occurred while forking clang for assembling).
> [asm] Transform options for assembler

- src/driver/AmdCompiler.cpp
+ switched on by default (clang and lld executables are not needed)
+ struct AssemblerInvocation introduction
+ methods PrepareAssembler, ExecuteAssembler and ExecuteCompiler are added
+ related code refactoring
P.S.
export AMD_OCL_IN_PROCESS=0 disables in-process for all compilation/linking routines, including assembling.
> [asm][in-process] Implement assembling in-process

- src/driver/AmdCompiler.cpp
Follow up for https://github.com/llvm-mirror/llvm/commit/80e97ed58226a95685791bdb05ce13bd7c3cb6fc
> OpenCL Driver: Fix build for upcoming merge.

- src/driver/CMakeLists.txt
- src/roc-cl/CMakeLists.txt
> Include LLVM_CONFIG_INCLUDE_DIR and LLVM_MAIN_INCLUDE_DIR

- CMakeLists.txt
This is a preparation for enabling ccache in our Jenkins jobs.
> Use ccache if ROCM_OPENCL_DRIVER_CCACHE_BUILD=ON
